email: athiporn1990@gmail.com
aka: BlackDragon
github_url: https://github.com/AthipornP
gitlab_url: https://gitlab.com/AthipornP
facebook_url: https://www.facebook.com/athiporn.phumnicom
orcid_url: https://orcid.org/0000-0003-0532-3733
keybase_url: https://keybase.io/athiporn
repl_url: https://repl.it/@AthipornPhumnic
remote_theme: "AthipornP/forty-jekyll-theme"
baseurl: "/"
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10